# Generated by Django 2.1.5 on 2019-03-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0002_auto_20190317_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='catagories',
            field=models.CharField(default='place', max_length=255),
        ),
    ]
