# Generated by Django 2.1.5 on 2019-03-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0005_backer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_funds',
        ),
        migrations.AddField(
            model_name='backer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='backers', to='crowdfunder.Project'),
            preserve_default=False,
        ),
    ]
