# Generated by Django 2.1.5 on 2019-03-19 17:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0006_auto_20190318_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_raised', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='crowdfunder.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='backer',
            name='amount_given',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Please Enter A Value Higher Than Zero.')]),
        ),
    ]
