# Generated by Django 2.1.7 on 2019-03-19 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0006_auto_20190318_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crowdfunder.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='backer',
            name='amount_given',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Please Enter A Value Higher Than Zero.')]),
        ),
    ]
