# Generated by Django 2.1.5 on 2019-03-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0007_auto_20190319_1731'),
        ('crowdfunder', '0004_userprofile'),
        ('crowdfunder', '0007_auto_20190318_2132'),
    ]

    operations = [
    ]
