# Generated by Django 2.1.7 on 2019-03-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0004_userprofile'),
        ('crowdfunder', '0007_auto_20190318_2132'),
    ]

    operations = [
    ]
