# Generated by Django 2.1.5 on 2019-03-19 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0008_merge_20190319_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='category',
            name='project',
        ),
        migrations.AlterField(
            model_name='backer',
            name='amount_given',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Please Enter A Value Higher Than Zero.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='catagories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crowdfunder.Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_goal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Please Enter A Value Higher Than Zero.')]),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
