# Generated by Django 2.1.7 on 2019-03-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0007_auto_20190319_1917'),
        ('crowdfunder', '0010_category_name'),
        ('crowdfunder', '0008_merge_20190319_2046'),
    ]

    operations = [
    ]
